version: "3.8"

services:
  russian-cup-backend:
    container_name: "russian-cup-backend-django"
    build:
      context: ..
      dockerfile: deployments/Dockerfile
    volumes:
      - static_volume:/app/fsp-pro/staticfiles
    env_file:
      - "../.env"
    ports:
      - "9090:9090"
    networks:
      - russian_cup_backend_net
    restart: on-failure

  nginx-russian-cup:
    image: nginx:latest
    container_name: nginx-russian-cup
    ports:
      - "4443:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - static_volume:/app/fsp-pro/staticfiles
    networks:
      - russian_cup_backend_net

  russian-cup-pg:
    container_name: "russian-cup-pg"
    image: postgres:15.0
    ports:
      - "5433:5432"
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: b1fddce8ae427c0d
    volumes:
      - "pgdata:/var/lib/postgresql/data"
    healthcheck:
      test: pg_isready -d postgres -U postgres
      retries: 5
      interval: 5s
      timeout: 7s
    networks:
      - russian_cup_backend_net

volumes:
  static_volume:
  pgdata:

networks:
  russian_cup_backend_net:
    external: true



